# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# our million, find the sum of the even-valued terms.


# Solution #1
# ===========

# result = 0
# fib = [1, 2, 3]
# n = 5
# while n < 4000000:
#     n = fib[-1]+fib[-2]
#     if n < 4000000:
#         fib.append(n)
#         if n % 2 == 0:
#             result += n
#     print(fib)


# Solution #2
# ===========

sum = 0
i, j = 1, 2
while j < 4000000:
    if j % 2 == 0:
        sum += j
    i, j = j, j + i

print(sum)

